# More info: https://github.com/prometheus-community/helm-charts/blob/main/charts/prometheus/values.yaml
global:
  scrape_interval: 5m
  scrape_timeout: 30s
  evaluation_interval: 5m

server:
  retention: "7d"

  persistentVolume:
    enabled: true
    size: 100Gi

  podLabels:
    sidecar.istio.io/inject: 'false'

  statefulSet:
    enabled: true

  resources:
    requests:
      cpu: 500m
      memory: 4Gi
    limits:
      cpu: 1000m
      memory: 7Gi
