global:
  scrape_interval: 5m
  scrape_timeout: 30s
  evaluation_interval: 5m

server:
  extraArgs:
    storage.local.retention: 168h

  persistentVolume:
    enabled: true
    size: 100Gi

  podLabels:
    sidecar.istio.io/inject: "false"

  statefulSet:
    enabled: true

  resources:
    requests:
      cpu: 500m
      memory: 4Gb
    limits:
      cpu: 1000m
      memory: 7Gi