# Values for the istio-public-ingressgateway addon
# See: https://github.com/istio/istio/blob/release-1.24/manifests/charts/gateway/values.yaml

name: istio-public-ingressgateway

labels:
  app: istio-public-ingressgateway
  istio: istio-public-ingressgateway

imagePullPolicy: IfNotPresent

resources:
  limits:
    cpu: 1000m
    memory: 1024Mi
  requests:
    cpu: 256m
    memory: 512Mi

service:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-east-1:492684252576:certificate/1df12f14-ad70-480e-bf15-368fc6e07ae6
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: https

# HPA for the ingress gateway
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80

strategy:
  rollingUpdate:
    maxSurge: 100%
    maxUnavailable: 25%

