# meshConfig defines runtime configuration of components, including Istiod and istio-agent behavior
# See https://istio.io/docs/reference/config/istio.mesh.v1alpha1/ for all available options
global:
  hub: gcr.io/istio-release # TODO: Use ECR for production
  imagePullPolicy: IfNotPresent
  proxy:
    autoInject: disabled

meshConfig:
  enableTracing: true
  defaultConfig:
    gatewayTopology:
      numTrustedProxies: 1
    interceptionMode: TPROXY
  extensionProviders:
  - name: otel-tracing
    opentelemetry:
      port: 4317
      service: open-telemetry-collector.monitoring.svc.cluster.local

traceSampling: 1.0

autoscaleMin: 1
autoscaleMax: 5

# Resources for a small pilot install
resources:
  requests:
    cpu: 250m
    memory: 1024Mi

affinity:
  nodeAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 90
        preference:
          matchExpressions:
            - key: eks.amazonaws.com/capacityType
              operator: In
              values:
                - ON_DEMAND
      - weight: 10
        preference:
          matchExpressions:
            - key: karpenter.sh/capacity-type
              operator: In
              values:
                - on-demand
